
SELECT ename,
    CASE
    WHEN job = "SALESMAN" THEN "SALESPERSON"
    
    ELSE job
END AS NEWJOB
FROM emp
ORDER BY job,ename

/*FORD	ANALYST
SCOTT	ANALYST
ADAMS	CLERK
JAMES	CLERK
MILLER	CLERK
SMITH	CLERK
BLAKE	MANAGER
CLARK	MANAGER
JONES	MANAGER
KING	PRESIDENT
ALLEN	SALESPERSON
MARTIN	SALESPERSON
TURNER	SALESPERSON
WARD	SALESPERSON


Execution finished without errors.
Result: 14 rows returned in 18ms
At line 1: