
SELECT e.ename, d.loc, d.dname
from emp e, dept d
where e.comm is NOT NULL
ORDER by e.ename

/*ALLEN	NEW YORK	ACCOUNTING
ALLEN	DALLAS	RESEARCH
ALLEN	CHICAGO	SALES
ALLEN	BOSTON	OPERATIONS
MARTIN	NEW YORK	ACCOUNTING
MARTIN	DALLAS	RESEARCH
MARTIN	CHICAGO	SALES
MARTIN	BOSTON	OPERATIONS
TURNER	NEW YORK	ACCOUNTING
TURNER	DALLAS	RESEARCH
TURNER	CHICAGO	SALES
TURNER	BOSTON	OPERATIONS
WARD	NEW YORK	ACCOUNTING
WARD	DALLAS	RESEARCH
WARD	CHICAGO	SALES
WARD	BOSTON	OPERATIONS

Execution finished without errors.
Result: 16 rows returned in 14ms
At line 1: